### ISSUE TITLE
Add function to upload assets to Contensis

### ISSUE THREAD

**Issue by PDerid** [contensis/contensis-management-api#66]
Hi

Would it be possible to add a function to the Contensis management client to upload assets?
Currently, it seems that the only way to do this, is by using the [HTTP method](https://www.contensis.com/help-and-docs/apis/management-js/assets/upload-asset-file).

Our project is nicely structured by using the client everywhere, but for assets we need to use one HTTP request we would like to remove in favor of the client.

Is this possible to do?

**Comment by nflatley-zengenti** [comment]
Hi there,

It is already possible to upload assets to Contensis, however this is not an operation available in the browser for security reasons and is only available in a server/script NodeJS context.

To expose the asset methods in your management client you need to import and create the correct client type.

The package README has been recently updated to make this clearer

You need to call NodeJsClient.create() instead of the normal Client.create() and you will see asset methods under your `client.entries.*`. The client is created with the same configuration as the default one

We recognise the official documentation is lacking a useful example using these methods and we will review this in due course.

In the meantime I hope this example pasted below is useful to guide you on how I have used these methods in the Contensis CLI

```
import { NodejsClient } from 'contensis-management-api/lib/client';
```

``` typescript
  CreateAsset = (asset: Entry, assetFilePath: string, parentNodePath: string) =>
    this.assetClient.entries.createAsset(asset, assetFilePath, parentNodePath);
```

``` typescript
  UpdateOrCreateAsset = async (
    existing: Entry | undefined,
    asset: Entry,
    assetFilePath: string,
    parentNodePath: string
  ): Promise<[AppError | null, Entry | undefined]> => {
    let err: AppError | null = null;
    let savedAsset: Entry | undefined;
    if (!existing) {
      Logger.info(
        `[assets] [create:${asset.sys.contentTypeId}] '${asset?.entryTitle}' | ${asset.sys.id}`
      );
      // calling the management method to create a new asset
      [err, savedAsset] = await to(
        this.assetClient.entries.createAsset(
          asset,
          assetFilePath,
          parentNodePath
        )
      );
      if (savedAsset)
        Logger.success(
          `[assets] [created:${savedAsset.sys.contentTypeId}] '${savedAsset?.entryTitle}' | ${savedAsset.sys.id}`
        );
    }
    if (existing) {
      Logger.info(
        `[assets] [update:${existing.sys.contentTypeId}] '${existing?.entryTitle}' | ${existing.sys.id}`
      );
      // calling the management method to update an existing asset
      [err, savedAsset] = await to(
        this.assetClient.entries.updateAsset(
          { ...asset, sys: existing.sys },
          assetFilePath
        )
      );
      if (savedAsset)
        Logger.success(
          `[entries] [updated:${savedAsset.sys.contentTypeId}] '${savedAsset?.entryTitle}' | ${savedAsset.sys.id}`
        );
    }

    return [err, savedAsset];
  };
```
